---
- name: Pull Nginx image
  docker_image:
    name: "{{ nginx_image }}"
    source: pull

- name: Run Nginx container
  docker_container:
    name: "{{ nginx_container_name }}"
    image: "{{ nginx_image }}"
    state: started
    ports: "{{ nginx_ports }}"
